// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const weatherCreate = `-- name: WeatherCreate :one
INSERT INTO weather (
	id,
	observed_at,
	temperature,
	apparent_temperature,
	humidity,
	precipitation,
	rain,
	snowfall,
	cloud_cover,
	wind_speed,
	wind_gusts,
	wind_direction,
	condition_code,
	condition
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, created_at, updated_at, observed_at, temperature, apparent_temperature, humidity, precipitation, rain, snowfall, cloud_cover, wind_speed, wind_gusts, wind_direction, condition_code, condition
`

type WeatherCreateParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	ObservedAt          time.Time `db:"observed_at" json:"observed_at"`
	Temperature         float64   `db:"temperature" json:"temperature"`
	ApparentTemperature float64   `db:"apparent_temperature" json:"apparent_temperature"`
	Humidity            int64     `db:"humidity" json:"humidity"`
	Precipitation       float64   `db:"precipitation" json:"precipitation"`
	Rain                float64   `db:"rain" json:"rain"`
	Snowfall            float64   `db:"snowfall" json:"snowfall"`
	CloudCover          int64     `db:"cloud_cover" json:"cloud_cover"`
	WindSpeed           float64   `db:"wind_speed" json:"wind_speed"`
	WindGusts           float64   `db:"wind_gusts" json:"wind_gusts"`
	WindDirection       int64     `db:"wind_direction" json:"wind_direction"`
	ConditionCode       int64     `db:"condition_code" json:"condition_code"`
	Condition           string    `db:"condition" json:"condition"`
}

func (q *Queries) WeatherCreate(ctx context.Context, arg WeatherCreateParams) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherCreate,
		arg.ID,
		arg.ObservedAt,
		arg.Temperature,
		arg.ApparentTemperature,
		arg.Humidity,
		arg.Precipitation,
		arg.Rain,
		arg.Snowfall,
		arg.CloudCover,
		arg.WindSpeed,
		arg.WindGusts,
		arg.WindDirection,
		arg.ConditionCode,
		arg.Condition,
	)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Temperature,
		&i.ApparentTemperature,
		&i.Humidity,
		&i.Precipitation,
		&i.Rain,
		&i.Snowfall,
		&i.CloudCover,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.ConditionCode,
		&i.Condition,
	)
	return i, err
}

const weatherFind = `-- name: WeatherFind :one
SELECT id, created_at, updated_at, observed_at, temperature, apparent_temperature, humidity, precipitation, rain, snowfall, cloud_cover, wind_speed, wind_gusts, wind_direction, condition_code, condition FROM weather WHERE id = ?
`

func (q *Queries) WeatherFind(ctx context.Context, id uuid.UUID) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherFind, id)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Temperature,
		&i.ApparentTemperature,
		&i.Humidity,
		&i.Precipitation,
		&i.Rain,
		&i.Snowfall,
		&i.CloudCover,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.ConditionCode,
		&i.Condition,
	)
	return i, err
}
